### ISSUE TITLE
TODO for first release

### ISSUE THREAD

**Issue by litencatt** [litencatt/uniar#1]
## Major functions to implement
- CLI
- Support SQLite

### setup
- [x] setup
- [x] init db
- [x] regist user's scenes, bonds, discography, office bonus statuses

### list
- [x] group
- [x] live
- [x] member
- [x] music
- [x] scene

#### Filter and Sort
- Filter by
    - color
    - have ot not have
- Sort Key
    - Center Skill

### regist
- [ ] *group
- [x] *live
- [ ] *member
- [x] *music
- [x] scene

### update
- [ ] member(bonds, discography, graduation, ...)
- [ ] *music(for Pro+, ...)
- [ ] scene(for SSR+, music bonus, ...)

*: for Admin
